In [2]:
1+1

2

# 제목
본문
* 항목1
* 항목2

In [3]:
1 + 1 # 더하깈ㅋㅋ

2

In [4]:
1 + 1 더하기!!!!

SyntaxError: invalid syntax (<ipython-input-4-cf5da18b053c>, line 1)

In [5]:
1234535

1234535

In [6]:
123e2

12300.0

In [7]:
123 * 10 ** 2

12300

In [8]:
'ㅁㄴㅇㄹㄴㄹ'

'ㅁㄴㅇㄹㄴㄹ'

In [9]:
"ㅁㄴㅇㄹㄴㅇㅁㄹ"

'ㅁㄴㅇㄹㄴㅇㅁㄹ'

In [10]:
'it's mine'

SyntaxError: invalid syntax (<ipython-input-10-ec3d9fc6d2af>, line 1)

In [11]:
'it\'s mine'

"it's mine"

In [12]:
"it's mine"

"it's mine"

In [13]:
'abc'
"abc"
'''abc'''

'abc'

In [15]:
'abc'
"ㅋㅋㅋ"
'''ㅎㅎㅎ'''

'ㅎㅎㅎ'

In [16]:
print('abc')
print("ㅋㅋㅋ")
print('''ㅎㅎㅎ''')

abc
ㅋㅋㅋ
ㅎㅎㅎ


In [17]:
tx = "Hello!"

In [18]:
tx

'Hello!'

In [19]:
tx[0]

'H'

In [21]:
tx[0:4] # 4 - 1

'Hell'

In [22]:
tx[-1]

'!'

In [23]:
5 % 2

1

In [24]:
5 / 2

2.5

In [25]:
5 // 2

2

In [26]:
10 ** 2

100

In [27]:
4 ** 0.5

2.0

In [28]:
5 >= 3

True

In [29]:
1 > 3

False

In [30]:
aa = [1, 2, 3]
bb = [4, 5, 6]

In [31]:
aa + bb

[1, 2, 3, 4, 5, 6]

In [32]:
"abc" + "def"

'abcdef'

In [33]:
aa * 2

[1, 2, 3, 1, 2, 3]

In [34]:
import numpy as np

In [35]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
arr_a

array([1, 2, 3])

In [36]:
arr_a + arr_b

array([5, 7, 9])

In [37]:
aa

[1, 2, 3]

In [38]:
aa[0] = 55
aa

[55, 2, 3]

In [39]:
aa[0]

55

In [40]:
mm = [1, 2, 3]
mm

[1, 2, 3]

In [41]:
mm.index(1)

0

In [42]:
mm.index(5)

ValueError: 5 is not in list

In [43]:
"+".join(["A", "B", "C"])

'A+B+C'

In [44]:
"y ~ " + "+".join(["A", "B", "C"])

'y ~ A+B+C'

In [45]:
import pandas as pd

In [46]:
ser = pd.Series(["A", "B", "C"])

In [47]:
"+".join(ser)

'A+B+C'

In [62]:
for n in range(3):
    print(n)

0
1
2


In [63]:
udf_01()

NameError: name 'udf_01' is not defined

In [65]:
def udf_01(a):
    print(a)

In [66]:
udf_01()

TypeError: udf_01() missing 1 required positional argument: 'a'

In [67]:
import os

In [68]:
os.listdir()

['.ipynb_checkpoints',
 'AWS_sample.txt',
 'bank.csv',
 'bike.csv',
 'bike.json',
 'bike_rental.csv',
 'bike_weather.csv',
 'classification_data_01.csv',
 'class_200622.ipynb',
 'class_scores.csv',
 'diabetes.csv',
 'diamonds.csv',
 'elec_load.csv',
 'iris_missing.csv',
 'iris_xlsx.xlsx',
 'join_list.csv',
 'join_room.csv',
 'linear_regression_01.csv',
 'logistic_regression_01.csv',
 'rating_chocobar.csv',
 'regex_example_df.csv',
 'traffic_accident.txt',
 'traffic_highway.csv']

In [1]:
aa

NameError: name 'aa' is not defined

In [2]:
import numpy as np

In [ ]:
np.array()

In [3]:
print(np.array.__doc__)

array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is n

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [6]:
arr + 5

array([6, 7, 8])

In [7]:
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [8]:
# arr = np.array([1, 2, 3], [4, 5, 6])
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
nums = [1, 2, 2, 5, 8, 8]

In [48]:
np.unique(nums)

array([1, 2, 5, 8])

In [49]:
set(nums)'/;./l,kmj,hnbgfvdcsxaz'

{1, 2, 5, 8}

In [50]:
list(set(nums))

[8, 1, 2, 5]

In [42]:
np.random.seed(123)
np.random.normal(loc = 0, scale = 1, size = 5)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [51]:
range(3)

range(0, 3)

In [52]:
np.arange(4, 8)

array([4, 5, 6, 7])

In [56]:
np.array([3, 5, 7, 9]) >= 7

array([False, False,  True,  True])

In [55]:
np.where(np.array([3, 5, 7, 9]) >= 7, "OK!", "ㅠㅠ")

array(['ㅠㅠ', 'ㅠㅠ', 'OK!', 'OK!'], dtype='<U3')

In [57]:
np.r_[1:5, 7, 10, 15:20]

array([ 1,  2,  3,  4,  7, 10, 15, 16, 17, 18, 19])

In [58]:
import pandas as pd

In [59]:
ser = pd.Series([2, 4, 6, 8])
ser

0    2
1    4
2    6
3    8
dtype: int64

In [60]:
ser.values

array([2, 4, 6, 8], dtype=int64)

In [61]:
ser = pd.Series([2, 4, 8, 9, 15])
ser

0     2
1     4
2     8
3     9
4    15
dtype: int64

In [62]:
ser.idxmin()

0

In [63]:
ser2 = pd.Series(np.arange(1, 7))
ser2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [64]:
ser2 + "월"

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [65]:
2 + "월"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [66]:
str(2) + "월"

'2월'

In [67]:
ser2.astype("str") + "월"

0    1월
1    2월
2    3월
3    4월
4    5월
5    6월
dtype: object

In [68]:
ser2.reset_index()

index  0
0      0  1
1      1  2
2      2  3
3      3  4
4      4  5
5      5  6

In [71]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
df = pd.DataFrame(np.arange(6).reshape(3, 2),
                  columns = ["aa", "bb"])
df

aa  bb
0   0   1
1   2   3
2   4   5

In [73]:
df["aa"]

0    0
1    2
2    4
Name: aa, dtype: int32

In [74]:
type(df["aa"])

pandas.core.series.Series

In [75]:
df.columns[1]

'bb'

In [77]:
df.columns = ["xx", "yy"]
df

xx  yy
0   0   1
1   2   3
2   4   5

In [81]:
df = df.rename(columns = {"xx": "obs"})
df

obs  yy
0    0   1
1    2   3
2    4   5

In [82]:
pd.__version__

'0.23.4'

In [ ]:
# 1.0.5

In [84]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [85]:
import os
os.listdir()

['.ipynb_checkpoints',
 'AWS_sample.txt',
 'bank.csv',
 'bike.csv',
 'bike.json',
 'bike_rental.csv',
 'bike_weather.csv',
 'classification_data_01.csv',
 'class_200622.ipynb',
 'class_scores.csv',
 'diabetes.csv',
 'diamonds.csv',
 'elec_load.csv',
 'iris_missing.csv',
 'iris_xlsx.xlsx',
 'join_list.csv',
 'join_room.csv',
 'linear_regression_01.csv',
 'logistic_regression_01.csv',
 'rating_chocobar.csv',
 'regex_example_df.csv',
 'traffic_accident.txt',
 'traffic_highway.csv']

In [90]:
df = pd.read_csv("AWS_sample.txt", sep = "#")
df.iloc[:3, ]

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =
2     108  2016-07-01 02  23.7   3.8  =

In [92]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [93]:
df_sub = df[df["season"] == 1]
df_sub.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [94]:
df_sub["season"].unique()

array([1], dtype=int64)

In [95]:
set(df_sub["season"])

{1}

In [96]:
len(df_sub)

2686

In [97]:
df_sub.shape

(2686, 12)

In [98]:
df_sub.shape[0]

2686

In [99]:
df_s13 = df[df["season"].isin([1, 3])]
df_s13.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [100]:
df_s13["season"].unique()

array([1, 3], dtype=int64)

In [101]:
df.iloc[:3, 4:]

weather  temp   atemp  humidity  windspeed  casual  registered  count
0        1  9.84  14.395        81        0.0       3          13     16
1        1  9.02  13.635        80        0.0       8          32     40
2        1  9.02  13.635        80        0.0       5          27     32

In [102]:
df.loc[df["humidity"] == 100, :"humidity"] # row조건, coㅣ조건

datetime  season  holiday  workingday  weather   temp  \
26     2011-01-02 02:00:00       1        0           0        2  17.22   
464    2011-02-02 10:00:00       1        0           1        2   9.02   
529    2011-02-05 05:00:00       1        0           0        3   8.20   
530    2011-02-05 06:00:00       1        0           0        3   8.20   
532    2011-02-05 08:00:00       1        0           0        3   8.20   
533    2011-02-05 09:00:00       1        0           0        3   8.20   
534    2011-02-05 10:00:00       1        0           0        3   8.20   
535    2011-02-05 11:00:00       1        0           0        3   9.02   
536    2011-02-05 12:00:00       1        0           0        3   9.02   
537    2011-02-05 13:00:00       1        0           0        3   9.02   
538    2011-02-05 14:00:00       1        0           0        3   9.02   
539    2011-02-05 15:00:00       1        0           0        3   9.02   
540    2011-02-05 16:00:00       1        0           0        3   9.02   
541    2011-02-05 17:00:00       1        0           0        2   9.84   
545    2011-02-05 21:00:00       1        0           0        1  10.66   
580    2011-02-07 08:00:00       1        0           1        2   6.56   
978    2011-03-05 05:00:00       1        0           0        2  12.30   
979    2011-03-05 06:00:00       1        0           0        2  12.30   
980    2011-03-05 07:00:00       1        0           0        2  12.30   
981    2011-03-05 08:00:00       1        0           0        2  12.30   
1003   2011-03-06 07:00:00       1        0           0        3  17.22   
1004   2011-03-06 08:00:00       1        0           0        2  16.40   
1005   2011-03-06 09:00:00       1        0           0        2  17.22   
1006   2011-03-06 10:00:00       1        0           0        2  17.22   
1007   2011-03-06 11:00:00       1        0           0        2  17.22   
1010   2011-03-06 14:00:00       1        0           0        3  18.04   
1011   2011-03-06 15:00:00       1        0           0        3  18.04   
1012   2011-03-06 16:00:00       1        0           0        3  14.76   
1013   2011-03-06 17:00:00       1        0           0        3  13.94   
1014   2011-03-06 18:00:00       1        0           0        3  13.12   
...                    ...     ...      ...         ...      ...    ...   
5113   2011-12-07 03:00:00       4        0           1        3  18.86   
5114   2011-12-07 04:00:00       4        0           1        3  18.86   
5115   2011-12-07 05:00:00       4        0           1        3  18.86   
5116   2011-12-07 06:00:00       4        0           1        3  19.68   
5117   2011-12-07 07:00:00       4        0           1        3  18.04   
5118   2011-12-07 08:00:00       4        0           1        3  18.04   
5119   2011-12-07 09:00:00       4        0           1        3  18.04   
5120   2011-12-07 10:00:00       4        0           1        3  18.04   
5121   2011-12-07 11:00:00       4        0           1        3  18.04   
5122   2011-12-07 12:00:00       4        0           1        3  18.04   
5123   2011-12-07 13:00:00       4        0           1        3  18.04   
5124   2011-12-07 14:00:00       4        0           1        3  18.04   
5127   2011-12-07 17:00:00       4        0           1        3  16.40   
6266   2012-02-17 08:00:00       1        0           1        2  10.66   
6267   2012-02-17 09:00:00       1        0           1        2  10.66   
6720   2012-03-17 07:00:00       1        0           0        2  16.40   
9571   2012-10-03 04:00:00       4        0           1        2  24.60   
10605  2012-12-08 07:00:00       4        0           0        2  14.76   
10618  2012-12-08 20:00:00       4        0           0        2  14.76   
10619  2012-12-08 21:00:00       4        0           0        2  14.76   
10642  2012-12-09 20:00:00       4        0           0        3  14.76   
10643  2012-12-09 21:00:00       4        0

In [104]:
df["casual"].quantile(0.99) # 99th percentile, 제 99 백분위수

240.14999999999964

In [106]:
df_sub = df.loc[df["casual"] >= df["casual"].quantile(0.99), :]
df_sub.head(2)

datetime  season  holiday  workingday  weather   temp  \
2751  2011-07-03 13:00:00       3        0           0        1  32.80   
2775  2011-07-04 13:00:00       3        1           0        2  31.98   

       atemp  humidity  windspeed  casual  registered  count  
2751  38.635        59    15.0013     248         173    421  
2775  35.605        49     0.0000     242         181    423

In [116]:
df["casual"].quantile([0.25, 0.5, 0.75])  # 제 1, 제 2, 제 3 사분위수

0.25     4.0
0.50    17.0
0.75    49.0
Name: casual, dtype: float64

In [117]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [118]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
Sepal.Length    5 non-null float64
Sepal.Width     4 non-null float64
Petal.Length    4 non-null float64
Petal.Width     5 non-null float64
Species         5 non-null object
dtypes: float64(4), object(1)
memory usage: 280.0+ bytes


In [119]:
df_sub["Sepal.Width"]

0    NaN
1    3.0
2    3.2
3    3.1
4    3.6
Name: Sepal.Width, dtype: float64

In [121]:
df_sub["Sepal.Width"].isna()
df_sub["Sepal.Width"].isnull()
df_sub["Sepal.Width"].notna()
df_sub["Sepal.Width"].notnull()

0    False
1     True
2     True
3     True
4     True
Name: Sepal.Width, dtype: bool

In [122]:
df_sub["Sepal.Width"].isna().sum()

1

In [123]:
True + True

2

In [124]:
False + False

0

In [125]:
df_sub.loc[df_sub["Sepal.Width"].isna(), ]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [126]:
df_sub.loc[df_sub["Sepal.Width"].notna(), ]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [127]:
df_sub["Sepal.Width"]

0    NaN
1    3.0
2    3.2
3    3.1
4    3.6
Name: Sepal.Width, dtype: float64

In [128]:
df_sub["Sepal.Width"].mean()

3.225

In [129]:
df_sub.loc[df_sub["Sepal.Width"].isna(), ] # 1
df_sub[df_sub["Sepal.Width"].isna()] # 2

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa

In [132]:
df_sub.fillna(999)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1        999.0         999.0          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [134]:
df_mis = df.iloc[5:9, :-1] # 마지막 변수 제외
df_mis

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
5           5.4          3.9           1.7          0.4
6           NaN          NaN           NaN          NaN
7           5.0          3.4           NaN          0.2
8           4.4          2.9           1.4          0.2

In [135]:
df.iloc[5:9, ].drop("Species", axis = 1)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
5           5.4          3.9           1.7          0.4
6           NaN          NaN           NaN          NaN
7           5.0          3.4           NaN          0.2
8           4.4          2.9           1.4          0.2

In [138]:
df_mis.apply(lambda x: x.isna().sum(), axis = 1) # 각 row의 결측치 개수

5    0
6    4
7    1
8    0
dtype: int64

In [139]:
df_mis.apply(lambda x: x.isna().sum(), axis = 1) == df_mis.shape[1]

5    False
6     True
7    False
8    False
dtype: bool

In [141]:
bike = pd.read_csv("bike.csv")
bike.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [142]:
bike2 = bike.loc[:, ["season", "holiday", "temp"]]
bike2.head(2)

season  holiday  temp
0       1        0  9.84
1       1        0  9.02

In [144]:
# bike2.set_index(["season", "holiday"])

In [145]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [146]:
df_1 = df.head()
df_2 = df.tail()

In [147]:
df_bind = pd.concat([df_1, df_2])
df_bind.shape

(10, 12)

In [148]:
df_bind.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [149]:
pd.concat([df_1, df_2], axis = 1)

datetime  season  holiday  workingday weather  temp   atemp  \
0      2011-01-01 00:00:00     1.0      0.0         0.0     1.0  9.84  14.395   
1      2011-01-01 01:00:00     1.0      0.0         0.0     1.0  9.02  13.635   
2      2011-01-01 02:00:00     1.0      0.0         0.0     1.0  9.02  13.635   
3      2011-01-01 03:00:00     1.0      0.0         0.0     1.0  9.84  14.395   
4      2011-01-01 04:00:00     1.0      0.0         0.0     1.0  9.84  14.395   
10881                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   
10882                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   
10883                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   
10884                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   
10885                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   

       humidity  windspeed  casual  ...    holiday  workingday weather   temp  \
0          81.0        0.0     3.0  ...        NaN         NaN     NaN    NaN   
1          80.0        0.0     8.0  ...        NaN         NaN     NaN    NaN   
2          80.0        0.0     5.0  ...        NaN         NaN     NaN    NaN   
3          75.0        0.0     3.0  ...        NaN         NaN     NaN    NaN   
4          75.0        0.0     0.0  ...        NaN         NaN     NaN    NaN   
10881       NaN        NaN     NaN  ...        0.0         1.0     1.0  15.58   
10882       NaN        NaN     NaN  ...        0.0         1.0     1.0  14.76   
10883       NaN        NaN     NaN  ...        0.0         1.0     1.0  13.94   
10884       NaN        NaN     NaN  ...        0.0         1.0     1.0  13.94   
10885       NaN        NaN     NaN  ...        0.0         1.0     1.0  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0         NaN       NaN        NaN     NaN         NaN    NaN  
1         NaN       NaN        NaN     NaN         NaN    NaN  
2         NaN       NaN        NaN     NaN         NaN    NaN  
3         NaN       NaN        NaN     NaN         NaN    NaN  
4         NaN       NaN        NaN     NaN         NaN    NaN  
10881  19.695      50.0    26.0027     7.0       329.0  336.0  
10882  17.425      57.0    15.0013    10.0       231.0  241.0  
10883  15.910      61.0    15.0013     4.0       164.0  168.0  
10884  17.425      61.0     6.0032    12.0       117.0  129.0  
10885  16.665      66.0     8.9981     4.0        84.0   88.0  

[10 rows x 24 columns]

In [150]:
pd.concat([df_1, df_2.reset_index(drop = True)], axis = 1)

datetime  season  holiday  workingday weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0       1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0       1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0       1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0       1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0       1  9.84  14.395   

   humidity  windspeed  casual  ...    holiday  workingday weather   temp  \
0        81        0.0       3  ...          0           1       1  15.58   
1        80        0.0       8  ...          0           1       1  14.76   
2        80        0.0       5  ...          0           1       1  13.94   
3        75        0.0       3  ...          0           1       1  13.94   
4        75        0.0       0  ...          0           1       1  13.12   

    atemp  humidity  windspeed  casual  registered  count  
0  19.695        50    26.0027       7         329    336  
1  17.425        57    15.0013      10         231    241  
2  15.910        61    15.0013       4         164    168  
3  17.425        61     6.0032      12         117    129  
4  16.665        66     8.9981       4          84     88  

[5 rows x 24 columns]

In [151]:
df_axis = df.iloc[:4, 5:8]
df_axis

temp   atemp  humidity
0  9.84  14.395        81
1  9.02  13.635        80
2  9.02  13.635        80
3  9.84  14.395        75

In [152]:
df_axis.sum(axis = 0)

temp         37.72
atemp        56.06
humidity    316.00
dtype: float64

In [153]:
df_axis.sum(axis = 1)

0    105.235
1    102.655
2    102.655
3     99.235
dtype: float64