In [1]:
1 + 1

### 파이썬 시작하기

In [2]:
### 파이썬

### 파이썬
기본문법

In [3]:
2 + 2 # 더하기 ㅋㅋ

4

In [4]:
# 2 + 2 더하기?

객체(object)

In [5]:
a = "asdf"

In [6]:
a

'asdf'

In [7]:
print(a)

asdf


In [8]:
'abc'
"abd"

'abd'

In [9]:
print('abc')
print("abd")

abc
abd


In [10]:
print("aa", "bb")

aa bb


In [11]:
'it\'s mine'

"it's mine"

In [12]:
tx = "Hello!"
tx

'Hello!'

In [13]:
tx[4]

'o'

In [14]:
tx[0:4]

'Hell'

In [15]:
tx[-1] # 마이너스 부호는 '뒤에서~~~ 몇 번째'

'!'

In [16]:
tx[:-1] # 마지막에 있는 것을 제외한 나머지~~

'Hello'

In [17]:
aa = [1, 2, 3]
bb = [4, 5, 6]

In [18]:
aa + bb

[1, 2, 3, 4, 5, 6]

In [19]:
[5, 7, 9]

[5, 7, 9]

In [20]:
aa.extend(bb)

In [21]:
aa

[1, 2, 3, 4, 5, 6]

In [22]:
import numpy as np
arr_aa = np.array([1, 2, 3])
arr_bb = np.array([4, 5, 6])

In [23]:
arr_aa + arr_bb

array([5, 7, 9])

In [24]:
arr_bb.mean()

5.0

In [25]:
mm = [1, 2, 3]

In [26]:
mm.index(3)

2

In [27]:
# mm.index(5)

In [28]:
kk = [100, 200, 300]

In [29]:
kk.index(200)

1

In [30]:
nums = [1, 3, 5, 7, 9]

In [31]:
def udf_mean(x):
    return sum(x) / len(x)

In [32]:
udf_mean(nums)

5.0

In [33]:
"price ~ " + " + ".join(["col1", "col2", "col3"])

'price ~ col1 + col2 + col3'

In [34]:
"aaaa" + "bbbb"

'aaaabbbb'

In [35]:
score = 85

In [36]:
score >= 80

True

In [37]:
for n in range(3):
    print(n)

0
1
2


In [38]:
range(10)

range(0, 10)

In [39]:
for n in [0, 1, 2]:
    print(n)

0
1
2


In [40]:
for num in [0, 1, 2]:
    print(num)

0
1
2


In [41]:
for _ in [0, 1, 2]:
    print(_)

0
1
2


In [42]:
a = [2, 6, 7, 8, 9]

In [43]:
list_even = [num for num in a if num % 2 == 0]
list_even

[2, 6, 8]

In [44]:
5 % 2

1

In [45]:
list_even = []
for num in a:
    if num % 2 == 0:
        list_even = list_even + [num]
list_even

[2, 6, 8]

In [46]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [47]:
import numpy as np

In [48]:
np.array([2, 4, 6])

array([2, 4, 6])

In [49]:
# !pip install numpy

In [50]:
# np.array()

In [51]:
nums = [1, 2, 2, 5, 8, 8]

In [52]:
len(nums) # length 의 첫 세글자.

6

In [53]:
set(nums)

{1, 2, 5, 8}

In [54]:
len(set(nums))

4

In [55]:
# np.average()

In [56]:
np.random.seed(123)
# 다른 함수에는 random_state 라는 인자로 활용

In [57]:
np_rnorm = np.random.normal(loc = 2, scale = 2, size = 100)
print(np_rnorm.mean())
print(np_rnorm.std())

2.0542181469807193
2.256480940955922


In [58]:
np.random.seed(999)
np_rnorm = np.random.normal(loc = 2, scale = 2, size = 100)
print(np_rnorm.mean())
print(np_rnorm.std())

2.3792175311317623
1.9415875550249546


In [64]:
np.array([1, 2, 3, 4, 5, 6]) >= 4

array([False, False, False,  True,  True,  True])

In [60]:
np.where(np.array([1, 2, 3, 4, 5, 6]) >= 4, "ok", "no")

array(['no', 'no', 'no', 'ok', 'ok', 'ok'], dtype='<U2')

In [65]:
np.where(np.array([1, 2, 3, 4, 5, 6]) >= 4, 1, 0)

array([0, 0, 0, 1, 1, 1])

In [66]:
(np.array([1, 2, 3, 4, 5, 6]) >= 4) + 0

array([0, 0, 0, 1, 1, 1])

In [67]:
(np.array([1, 2, 3, 4, 5, 6]) >= 4) * 1

array([0, 0, 0, 1, 1, 1])

In [61]:
np.r_[2:5, 8, 20:25]

array([ 2,  3,  4,  8, 20, 21, 22, 23, 24])

In [63]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [62]:
np.arange(3, 20, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
import pandas as pd

In [69]:
ser2 = pd.Series([2, 3, 2, 9, 8, 9, 8])

In [70]:
ser2.idxmax()

3

In [71]:
ser2.idxmin()

0

In [72]:
12 + "월"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [74]:
"12" + "월"

'12월'

In [73]:
str(12) + "월"

'12월'

In [75]:
ser2.astype("str") + "월"

0    2월
1    3월
2    2월
3    9월
4    8월
5    9월
6    8월
dtype: object

In [76]:
pd.DataFrame([[1, 2],
              [3, 4],
              [5, 6]],
             columns = ["col1", "col2"])

col1  col2
0     1     2
1     3     4
2     5     6

In [77]:
df = pd.DataFrame(np.arange(6).reshape(3, 2),
                  columns = ["aa", "bb"])

In [79]:
df.aa
df["aa"] # 결과가 Series

0    0
1    2
2    4
Name: aa, dtype: int32

In [80]:
df["aa"][1]
df["aa"][:2]

0    0
1    2
Name: aa, dtype: int32

In [81]:
df.loc[:, "aa"] # .loc 인덱서는 문자 또는 특정 조건을 입력으로 받음.

0    0
1    2
2    4
Name: aa, dtype: int32

In [82]:
df.iloc[:, 0] # .iloc 인덱서는 정수 입력만 가능(i -> integer)

0    0
1    2
2    4
Name: aa, dtype: int32

In [84]:
df2 = pd.DataFrame(np.arange(6).reshape(3, 2),
                   columns = ["ndim", "shape"])

In [85]:
df2

ndim  shape
0     0      1
1     2      3
2     4      5

In [86]:
df2.ndim

2

In [87]:
df2["ndim"]

0    0
1    2
2    4
Name: ndim, dtype: int32

In [88]:
pd.__version__

'0.25.1'

In [89]:
import os

In [90]:
os.listdir()

['.ipynb_checkpoints',
 'association_rule_data_01.csv',
 'AWS_sample.txt',
 'bank.csv',
 'bike.csv',
 'bike.json',
 'bike_rental.csv',
 'bike_weather.csv',
 'classification_data_01.csv',
 'class_201026.ipynb',
 'class_scores.csv',
 'dataset.zip',
 'diabetes.csv',
 'diamonds.csv',
 'elec_load.csv',
 'iris_missing.csv',
 'iris_xlsx.xlsx',
 'join_list.csv',
 'join_room.csv',
 'linear_regression_01.csv',
 'logistic_regression_01.csv',
 'rating_chocobar.csv',
 'regex_example_df.csv',
 'traffic_accident.txt',
 'traffic_highway.csv']

In [91]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [92]:
aws = pd.read_csv("AWS_sample.txt", sep = "#")
aws.iloc[:3]

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =
2     108  2016-07-01 02  23.7   3.8  =

In [93]:
pd.read_csv("AWS_sample.txt", nrows = 2)

AWS_ID#TM#TA#Wind#X.
0  108#2016-07-01 00#24.2#2.3#=
1  108#2016-07-01 01#24.3#2.3#=

In [ ]:
df[:2] # 정수 입력시 특정 row를 반환
# df.iloc[:2, ]

In [100]:
df[df["temp"] == 9.84].head(2)
# df.loc[df["temp"] == 9.84, ].head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
3        75        0.0       3          10     13

In [101]:
df = pd.read_csv("iris_missing.csv")
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
Sepal.Length    143 non-null float64
Sepal.Width     137 non-null float64
Petal.Length    136 non-null float64
Petal.Width     144 non-null float64
Species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


* 결측 표기 문제 
 - `NaN`: not a number
 - `NaT`: not a time
 - `null`: null, Null, NULL
 
 1.0버전 이상에서는 `NA`가 등장
 
 - `NA`: not available

In [103]:
ser = pd.Series([1, 2, np.nan, 100]) # 1.0 이상은 np.nan대신 pd.NA 권장
ser

0      1.0
1      2.0
2      NaN
3    100.0
dtype: float64

In [104]:
ser.mean()

34.333333333333336

In [106]:
df_sub = df.head()

In [107]:
df_sub.fillna(999)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1        999.0         999.0          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [108]:
df_sub["Sepal.Width"].fillna(999)

0    999.0
1      3.0
2      3.2
3      3.1
4      3.6
Name: Sepal.Width, dtype: float64

In [109]:
df_sub

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [110]:
df_mis = df.iloc[5:9, 0:-1] # 마지막 변수를 제외하고~~~
df_mis

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
5           5.4          3.9           1.7          0.4
6           NaN          NaN           NaN          NaN
7           5.0          3.4           NaN          0.2
8           4.4          2.9           1.4          0.2